# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Crewl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crewl
pod 'GoogleMaps', '7.1.0'
pod 'GooglePlaces', '7.1.0'

end
